version: "3"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "3001:3000"
    volumes:
      - /usr/app/node_modules
      - ./frontend:/usr/app/
    restart: always
    command: ["npm", "run", "dev"]
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: ["npm", "run", "start"]
    ports:
      - "4000:4000"
    volumes:
      - /usr/app/node_modules
      - ./backend:/usr/app/
  router:
    depends_on:
      - 'frontend'
      - 'backend'
    build:
      context: ./router
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3003:80"
    volumes:
      - ./router:/etc/nginx/conf.d/
  